global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'lexos-core'
    static_configs:
      - targets: ['lexos-core:8080']
    
  - job_name: 'vllm'
    static_configs:
      - targets: ['vllm:8000']
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
